#!/bin/bash
set -e

partitions=200     # 250
load=5000         # 250000
users=10
topics=2
numMsgs=$(( ${users} * ${topics} * ${load} ))

url=http://knkafkaconsole-default.kndev.us-south.containers.appdomain.cloud/

echo Cleaning...
curl -s http://knkafkaconsole-default.kndev.us-south.containers.appdomain.cloud?clear=1
seq 1 ${users} | while read u ; do
  seq 1 ${topics} | while read t ; do
    ./admin del-topic u${u}t${t} > /dev/null 2>&1 || true
  done
done
kubectl delete -f source.yaml > /dev/null 2>&1 || true

echo Hit enter to load
read a

echo Adding topic and sleep for 5
sourceTopics=$(
seq 1 ${users} | while read u ; do
  seq 1 ${topics} | while read t ; do
    ./admin add-topic u${u}t${t} ${partitions}
	echo -n "u${u}t${t},"
  done
done
)

sourceTopics=${sourceTopics%,}

echo sourceTopics:${sourceTopics}
sleep 5

echo
echo Loading ${load} messages
echo "Start date: `date`"
seq 1 ${users} | while read u ; do
  seq 1 ${topics} | while read t ; do
    ./admin load u${u}t${t} ${load}
  done
done
echo "End   date: `date`"

echo How many were actually added
# ./admin | grep u1t1.*size
count=$(./admin | grep "u[0-9]*t[0-9]*.*size" | sed "s/^.*size: \([0-9]*\).*$/\1/")
echo "--> ${count}"
echo "Should be: ${numMsgs}"
echo

echo Hit enter to start processing...
read a

echo Creating Kafka event source
SERVER=$(kubectl describe service/kafka-service | grep Ingress | sed "s/.*: *//")
cat source.yaml | sed "s/SERVER/$SERVER/g" | sed "s/TOPICS/${sourceTopics}/" | \
	kubectl apply -f -
echo

echo "Waiting for it to finish..."
echo "Start date: `date`"
while true ; do
  out=$(curl -qs ${url} | grep Total)
  echo -n ${out} | sed "s/^.*: \([0-9]*\).*$/\1,/g"
  echo ${out} | grep " ${numMsgs}\$" > /dev/null && break
  sleep 5
done
echo
echo "End   date: `date`"

echo
echo Check the pod logs for errors
kubectl logs -l serving.knative.dev/service=knkafkaservice -c user-container 
