apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers: SERVER:9092
  # topics: u1t1,u1t2,u2t1,u2t2
  topics: u1t1
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knkafkaservice
