apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers: SERVER:9092
  # bootstrapServers: 52.116.214.6:9092,,,
  topics: TOPICS
  # topics: u1t1,
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knkafkaservice
